# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ali Rokni's List of Github Projects
email: m_rokni@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  List of Github projects that I have created.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alirokni.github.io" # the base hostname & protocol for your site
twitter_username: rokni
github_username:  alirokni

# Build settings
markdown: kramdown
